owner: mubin-peweo # Your GitHub organization or username, where this repository lives
repo: cospo-status-page # The name of this repository

sites:
  - name: Cospo Backend
    url: http://194.42.98.6:8082
  - name: Cospo Admin Panel
    url: http://194.42.98.6:3003
  - name: Cospo Master DB
    url: http://194.42.98.6:8082/cospo-status/check_master_db_status
  - name: Cospo First Slave DB
    url: http://194.42.98.6:8082/cospo-status/check_first_slave_db_status
  - name: Cospo Second Slave DB
    url: http://194.42.98.6:8082/cospo-status/check_second_slave_db_status
  - name: Cospo Redis Server
    url: http://194.42.98.6:8082/cospo-status/check_redis_status

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  theme: light
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
